---
- name: Install apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - java
    - macvim
    - rightzoom
    - caffeine
    - alfred
    - google-chrome
    - vlc
    - firefox
    - dropbox
    - handbrake
    - skype
    - evernote
    - iterm2
    - intellij-idea-ce
  when: ansible_os_family == 'Darwin'

# TODO : Make this run conditionally. Also in an idempotent manner
#- name: Configure Janus for MacVim
#  shell: curl -Lo- https://bit.ly/janus-bootstrap | bash
