---
- name: install CLI tools
  homebrew: name={{ item }} state=present
  with_items:
    - brew-cask
    - wget
    - autojump
    - zsh
    - gradle
    - postgresql
  when: ansible_os_family == 'Darwin'

- name: install rvm and ruby
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby=2.5.1
